server:
  port: 9191

spring:
  application:
    name: bid-submission

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/rabbitmq


  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL91Dialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest



rabbitmq:
  exchange: rabbit.exchange
  queue: rabbit.queue
  routingkey: rabbit.routingkey




springdoc:
  swagger-ui:
    path: /swagger-ui


